openapi: 3.0.3
info:
  title: Sample API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1 # ローカルホストでの開発時に使用。
paths:
  /locations:
    get:
      summary: ロケーション一覧と図面情報を取得
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocationWithDrawings'
  /drawings:
    get:
      summary: 図面一覧を取得
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Drawing'
  /locations/{id}/drawings:
    put:
      summary: ロケーションに紐づく図面情報を更新
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Drawing'
      responses:
        '204':
          description: 更新成功
components:
  schemas:
    Drawing:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
        version:
          type: string
        status:
          type: string

    LocationWithDrawings:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        floor:
          type: string
        area:
          type: string
        drawings:
          type: array
          items:
            $ref: '#/components/schemas/Drawing'