// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package model

// Drawing defines model for Drawing.
type Drawing struct {
	Id      *string `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Status  *string `json:"status,omitempty"`
	Type    *string `json:"type,omitempty"`
	Version *string `json:"version,omitempty"`
}

// LocationWithDrawings defines model for LocationWithDrawings.
type LocationWithDrawings struct {
	Area     *string    `json:"area,omitempty"`
	Drawings *[]Drawing `json:"drawings,omitempty"`
	Floor    *string    `json:"floor,omitempty"`
	Id       *string    `json:"id,omitempty"`
	Name     *string    `json:"name,omitempty"`
}

// PutLocationsIdDrawingsJSONBody defines parameters for PutLocationsIdDrawings.
type PutLocationsIdDrawingsJSONBody = []Drawing

// PutLocationsIdDrawingsJSONRequestBody defines body for PutLocationsIdDrawings for application/json ContentType.
type PutLocationsIdDrawingsJSONRequestBody = PutLocationsIdDrawingsJSONBody
